var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/gerar-documento/route.js")
R.c("server/chunks/[root-of-the-server]__0zmfrqp._.js")
R.c("server/chunks/05m__formdata-node_lib_esm_File_0xdrem4.js")
R.c("server/chunks/05m__next_dist_esm_build_templates_app-route_1wssmm_.js")
R.c("server/chunks/[root-of-the-server]__1ls0rub._.js")
R.c("server/chunks/05m__@supabase_supabase-js_dist_index_mjs_14t80kj._.js")
R.c("server/chunks/[root-of-the-server]__1j5oouu._.js")
R.c("server/chunks/preveia__next-internal_server_app_api_gerar-documento_route_actions_0t0lz8m.js")
R.m(1334)
module.exports=R.m(1334).exports
