// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/aceite/[token]" | "/admin" | "/advogado/[slug]" | "/advogados" | "/agentes" | "/analise-previdenciaria" | "/assinatura" | "/blog" | "/chat" | "/clientes" | "/clientes/[id]" | "/configuracoes" | "/controladoria" | "/dashboard" | "/documentos" | "/equipe" | "/escolha" | "/ferramentas" | "/honorarios" | "/ia" | "/jurisdicao" | "/jurisprudencia" | "/login" | "/newsletter" | "/onboarding" | "/prazos" | "/privacidade" | "/processos" | "/recuperar" | "/redefinir" | "/registro" | "/suporte" | "/termos" | "/usuarios"
type AppRouteHandlerRoutes = "/api/aceite/[token]" | "/api/adicionar-inscrito" | "/api/aprovacoes-cliente" | "/api/aprovacoes-cliente/[id]/revogar" | "/api/aprovacoes-cliente/enviar-email" | "/api/cancelar-assinatura" | "/api/checar-pagamento" | "/api/clientes" | "/api/clientes/[id]" | "/api/consulta-processo" | "/api/criar-agente-custom" | "/api/criar-checkout-stripe" | "/api/criar-cobranca" | "/api/enviar-email" | "/api/enviar-newsletter" | "/api/extrair-documento-pdf" | "/api/extrair-pdf" | "/api/gerar-agente-custom" | "/api/gerar-documento" | "/api/gerar-sugestao-newsletter" | "/api/gerar-titulo-conversa" | "/api/ia-consultora" | "/api/manifest" | "/api/monitorar-processos" | "/api/sync-jurisprudencias" | "/api/validar-convite" | "/api/webhook-pagamento" | "/api/webhook-resend" | "/api/webhook-stripe"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/aceite/[token]": { "token": string; }
  "/admin": {}
  "/advogado/[slug]": { "slug": string; }
  "/advogados": {}
  "/agentes": {}
  "/analise-previdenciaria": {}
  "/api/aceite/[token]": { "token": string; }
  "/api/adicionar-inscrito": {}
  "/api/aprovacoes-cliente": {}
  "/api/aprovacoes-cliente/[id]/revogar": { "id": string; }
  "/api/aprovacoes-cliente/enviar-email": {}
  "/api/cancelar-assinatura": {}
  "/api/checar-pagamento": {}
  "/api/clientes": {}
  "/api/clientes/[id]": { "id": string; }
  "/api/consulta-processo": {}
  "/api/criar-agente-custom": {}
  "/api/criar-checkout-stripe": {}
  "/api/criar-cobranca": {}
  "/api/enviar-email": {}
  "/api/enviar-newsletter": {}
  "/api/extrair-documento-pdf": {}
  "/api/extrair-pdf": {}
  "/api/gerar-agente-custom": {}
  "/api/gerar-documento": {}
  "/api/gerar-sugestao-newsletter": {}
  "/api/gerar-titulo-conversa": {}
  "/api/ia-consultora": {}
  "/api/manifest": {}
  "/api/monitorar-processos": {}
  "/api/sync-jurisprudencias": {}
  "/api/validar-convite": {}
  "/api/webhook-pagamento": {}
  "/api/webhook-resend": {}
  "/api/webhook-stripe": {}
  "/assinatura": {}
  "/blog": {}
  "/chat": {}
  "/clientes": {}
  "/clientes/[id]": { "id": string; }
  "/configuracoes": {}
  "/controladoria": {}
  "/dashboard": {}
  "/documentos": {}
  "/equipe": {}
  "/escolha": {}
  "/ferramentas": {}
  "/honorarios": {}
  "/ia": {}
  "/jurisdicao": {}
  "/jurisprudencia": {}
  "/login": {}
  "/newsletter": {}
  "/onboarding": {}
  "/prazos": {}
  "/privacidade": {}
  "/processos": {}
  "/recuperar": {}
  "/redefinir": {}
  "/registro": {}
  "/suporte": {}
  "/termos": {}
  "/usuarios": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
