// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific
  const handler = {} as typeof import("../../app/(auth)/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/recuperar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar">> = Specific
  const handler = {} as typeof import("../../app/(auth)/recuperar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/redefinir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir">> = Specific
  const handler = {} as typeof import("../../app/(auth)/redefinir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registro">> = Specific
  const handler = {} as typeof import("../../app/(auth)/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/termos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/termos">> = Specific
  const handler = {} as typeof import("../../app/(auth)/termos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/analise-previdenciaria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analise-previdenciaria">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/analise-previdenciaria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/assinatura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assinatura">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/assinatura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clientes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clientes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/controladoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/controladoria">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/controladoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/documentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/documentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/equipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipe">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/equipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ferramentas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ferramentas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/honorarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/honorarios">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/honorarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ia">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/jurisdicao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jurisdicao">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/jurisdicao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/jurisprudencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jurisprudencia">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/jurisprudencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/newsletter">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/prazos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prazos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/prazos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/processos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/processos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/processos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/suporte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suporte">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/suporte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usuarios">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/aceite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aceite/[token]">> = Specific
  const handler = {} as typeof import("../../app/aceite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advogado/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advogado/[slug]">> = Specific
  const handler = {} as typeof import("../../app/advogado/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advogados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advogados">> = Specific
  const handler = {} as typeof import("../../app/advogados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/escolha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/escolha">> = Specific
  const handler = {} as typeof import("../../app/escolha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/aceite/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/aceite/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/aceite/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/adicionar-inscrito/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/adicionar-inscrito">> = Specific
  const handler = {} as typeof import("../../app/api/adicionar-inscrito/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/aprovacoes-cliente/[id]/revogar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/aprovacoes-cliente/[id]/revogar">> = Specific
  const handler = {} as typeof import("../../app/api/aprovacoes-cliente/[id]/revogar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/aprovacoes-cliente/enviar-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/aprovacoes-cliente/enviar-email">> = Specific
  const handler = {} as typeof import("../../app/api/aprovacoes-cliente/enviar-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/aprovacoes-cliente/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/aprovacoes-cliente">> = Specific
  const handler = {} as typeof import("../../app/api/aprovacoes-cliente/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cancelar-assinatura/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cancelar-assinatura">> = Specific
  const handler = {} as typeof import("../../app/api/cancelar-assinatura/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checar-pagamento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checar-pagamento">> = Specific
  const handler = {} as typeof import("../../app/api/checar-pagamento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/consulta-processo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consulta-processo">> = Specific
  const handler = {} as typeof import("../../app/api/consulta-processo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/criar-agente-custom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/criar-agente-custom">> = Specific
  const handler = {} as typeof import("../../app/api/criar-agente-custom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/criar-checkout-stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/criar-checkout-stripe">> = Specific
  const handler = {} as typeof import("../../app/api/criar-checkout-stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/criar-cobranca/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/criar-cobranca">> = Specific
  const handler = {} as typeof import("../../app/api/criar-cobranca/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enviar-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enviar-email">> = Specific
  const handler = {} as typeof import("../../app/api/enviar-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enviar-newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enviar-newsletter">> = Specific
  const handler = {} as typeof import("../../app/api/enviar-newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extrair-documento-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extrair-documento-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/extrair-documento-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extrair-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extrair-pdf">> = Specific
  const handler = {} as typeof import("../../app/api/extrair-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gerar-agente-custom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gerar-agente-custom">> = Specific
  const handler = {} as typeof import("../../app/api/gerar-agente-custom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gerar-documento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gerar-documento">> = Specific
  const handler = {} as typeof import("../../app/api/gerar-documento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gerar-sugestao-newsletter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gerar-sugestao-newsletter">> = Specific
  const handler = {} as typeof import("../../app/api/gerar-sugestao-newsletter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gerar-titulo-conversa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gerar-titulo-conversa">> = Specific
  const handler = {} as typeof import("../../app/api/gerar-titulo-conversa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ia-consultora/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ia-consultora">> = Specific
  const handler = {} as typeof import("../../app/api/ia-consultora/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/manifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manifest">> = Specific
  const handler = {} as typeof import("../../app/api/manifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitorar-processos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitorar-processos">> = Specific
  const handler = {} as typeof import("../../app/api/monitorar-processos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync-jurisprudencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-jurisprudencias">> = Specific
  const handler = {} as typeof import("../../app/api/sync-jurisprudencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/validar-convite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/validar-convite">> = Specific
  const handler = {} as typeof import("../../app/api/validar-convite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook-pagamento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-pagamento">> = Specific
  const handler = {} as typeof import("../../app/api/webhook-pagamento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook-resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-resend">> = Specific
  const handler = {} as typeof import("../../app/api/webhook-resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhook-stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook-stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhook-stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
