var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/clientes/route.js")
R.c("server/chunks/05m__13vc3vt._.js")
R.c("server/chunks/05m__next_0esk-b2._.js")
R.c("server/chunks/[root-of-the-server]__0ahiq59._.js")
R.c("server/chunks/05m__next_dist_046c9-6._.js")
R.c("server/chunks/05m__@supabase_supabase-js_dist_index_mjs_14t80kj._.js")
R.c("server/chunks/[root-of-the-server]__1ls0rub._.js")
R.c("server/chunks/preveia__next-internal_server_app_api_clientes_route_actions_1w64csm.js")
R.m(538566)
module.exports=R.m(538566).exports
