var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/extrair-documento-pdf/route.js")
R.c("server/chunks/[root-of-the-server]__04vagkq._.js")
R.c("server/chunks/05m__13vc3vt._.js")
R.c("server/chunks/[root-of-the-server]__1ls0rub._.js")
R.c("server/chunks/05m__next_dist_esm_build_templates_app-route_09jsttr.js")
R.c("server/chunks/05m__next_dist_046c9-6._.js")
R.c("server/chunks/05m__@supabase_supabase-js_dist_index_mjs_14t80kj._.js")
R.c("server/chunks/[root-of-the-server]__1j5oouu._.js")
R.c("server/chunks/05m__formdata-node_lib_esm_File_0xdrem4.js")
R.c("server/chunks/05m__next_0esk-b2._.js")
R.c("server/chunks/1nh6__next-internal_server_app_api_extrair-documento-pdf_route_actions_1q4ga7s.js")
R.m(4737)
module.exports=R.m(4737).exports
