var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/clientes/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04nl8on._.js")
R.c("server/chunks/ssr/05m__next_dist_0aywur0._.js")
R.c("server/chunks/ssr/05m__next_dist_esm_build_templates_app-page_0pd7j3b.js")
R.c("server/chunks/ssr/[root-of-the-server]__01_dj5c._.js")
R.c("server/chunks/ssr/05m__next_dist_1f4ywmj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvcdw_._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_0dj_j_g._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_forbidden_1qf2fsq.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_unauthorized_1diu637.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_global-error_0god72_.js")
R.c("server/chunks/ssr/preveia_app_(dashboard)_layout_tsx_1qx0zqz._.js")
R.c("server/chunks/ssr/preveia__next-internal_server_app_(dashboard)_clientes_[id]_page_actions_146ox8d.js")
R.m(899539)
module.exports=R.m(899539).exports
