var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/advogados/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ndog8j._.js")
R.c("server/chunks/ssr/05m__next_dist_esm_build_templates_app-page_1d7l2dt.js")
R.c("server/chunks/ssr/05m__076q_rz._.js")
R.c("server/chunks/ssr/05m__next_dist_0aywur0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1p7wwt3._.js")
R.c("server/chunks/ssr/05m__next_dist_1f4ywmj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvcdw_._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_0dj_j_g._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_forbidden_1qf2fsq.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_unauthorized_1diu637.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_global-error_0god72_.js")
R.c("server/chunks/ssr/preveia__next-internal_server_app_advogados_page_actions_13bct7w.js")
R.m(40689)
module.exports=R.m(40689).exports
