var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/controladoria/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-jtvy3._.js")
R.c("server/chunks/ssr/preveia_13beg9c._.js")
R.c("server/chunks/ssr/05m__next_dist_esm_build_templates_app-page_05kz5u5.js")
R.c("server/chunks/ssr/05m__@supabase_supabase-js_dist_index_mjs_03331xg._.js")
R.c("server/chunks/ssr/05m__next_dist_122a0ff._.js")
R.c("server/chunks/ssr/05m__next_dist_0aywur0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01_dj5c._.js")
R.c("server/chunks/ssr/05m__next_dist_1f4ywmj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uvcdw_._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_0dj_j_g._.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_forbidden_1qf2fsq.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_unauthorized_1diu637.js")
R.c("server/chunks/ssr/05m__next_dist_client_components_builtin_global-error_0god72_.js")
R.c("server/chunks/ssr/preveia_app_(dashboard)_layout_tsx_1qx0zqz._.js")
R.c("server/chunks/ssr/preveia__next-internal_server_app_(dashboard)_controladoria_page_actions_16k_0nc.js")
R.m(786609)
module.exports=R.m(786609).exports
