var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/documento-acesso/route.js")
R.c("server/chunks/[root-of-the-server]__1r8sdt_._.js")
R.c("server/chunks/05m__next_dist_046c9-6._.js")
R.c("server/chunks/05m__13vc3vt._.js")
R.c("server/chunks/[root-of-the-server]__1ls0rub._.js")
R.c("server/chunks/05m__@supabase_supabase-js_dist_index_mjs_14t80kj._.js")
R.c("server/chunks/05m__next_0esk-b2._.js")
R.c("server/chunks/preveia__next-internal_server_app_api_documento-acesso_route_actions_0j5o_cw.js")
R.m(266567)
module.exports=R.m(266567).exports
